"""Adding columns for notification service

Revision ID: 0e85998b940e
Revises: 9a295392ce74
Create Date: 2026-07-22 13:01:19.034832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e85998b940e'
down_revision: Union[str, Sequence[str], None] = '9a295392ce74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('is_notification_processed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notifications_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications_enabled')
    op.drop_column('jobs', 'is_notification_processed')
    # ### end Alembic commands ###
