"""Rename column preferred_countries

Revision ID: 423bcb92d5e9
Revises: ad16493b9b70
Create Date: 2026-08-11 00:49:34.311516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '423bcb92d5e9'
down_revision: Union[str, Sequence[str], None] = 'ad16493b9b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_locations', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('users', 'preferred_countries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_countries', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('users', 'preferred_locations')
    # ### end Alembic commands ###
