"""Fixed columns for notification service

Revision ID: 7ede6edd91b0
Revises: 0e85998b940e
Create Date: 2026-07-22 13:10:08.727770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ede6edd91b0'
down_revision: Union[str, Sequence[str], None] = '0e85998b940e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'is_notification_processed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('jobs', 'is_notification_processed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
