"""Adding verification columns to users

Revision ID: 9cccd674da17
Revises: 7ff4eaf63fe7
Create Date: 2026-07-20 16:39:19.368137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cccd674da17'
down_revision: Union[str, Sequence[str], None] = '7ff4eaf63fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_expires_at')
    op.drop_column('users', 'verification_code')
    # ### end Alembic commands ###
