"""Rename preferred_country

Revision ID: ad16493b9b70
Revises: be51a932eaa1
Create Date: 2026-08-11 00:18:35.633757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad16493b9b70'
down_revision: Union[str, Sequence[str], None] = 'be51a932eaa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_countries', postgresql.ARRAY(sa.String()), nullable=False))
    op.drop_column('users', 'preferred_country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_country', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('users', 'preferred_countries')
    # ### end Alembic commands ###
